runtime: python312
entrypoint: gunicorn -b :$PORT app:app --access-logfile - --error-logfile -

# Environment variables for Firebase (public values)
# Sensitive API keys are loaded from Google Cloud Secret Manager at runtime
env_variables:
  FIREBASE_AUTH_DOMAIN: "confessiones-c6ca5.firebaseapp.com"
  FIREBASE_PROJECT_ID: "confessiones-c6ca5"
  FIREBASE_STORAGE_BUCKET: "confessiones-c6ca5.firebasestorage.app"
  FIREBASE_MESSAGING_SENDER_ID: "973055633561"
  FIREBASE_APP_ID: "1:973055633561:web:f3f3c453669925fa42f008"

automatic_scaling:
  min_instances: 0
  max_instances: 1
